name: Build and deploy container app to Azure Web App - kdc-test

on:
  push:
    branches: # Run workflow on push to main branch
      - main
  workflow_dispatch: # Allow manual triggering of the workflow

# Important permissions for the workflow granted to github actions
# If it still doesn't work, check the container's permissions (or simply delete the image completely and try again)
permissions:
  packages: write # Set here: https://github.com/[organization]/[repository]/settings/actions
  contents: read

jobs:
  build: # Build and push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set timestamp
        id: vars
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/
          username: ${{ github.actor }} # GitHub username = GitHub actions actor
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub token generated by GitHub Actions

      - name: Build and push container image to registry (latest)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            ghcr.io/kulzer-dental/kdc-experimental-image:latest
            ghcr.io/kulzer-dental/kdc-experimental-image:${{ steps.vars.outputs.timestamp }}
          file: ./Dockerfile

  deploy: # Deploy the Docker image to Azure Web App
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "kdc-test"
          slot-name: "Production" # Use "Production" slot for deployment
          images: "ghcr.io/kulzer-dental/kdc-experimental-image:latest"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Log in to GitHub Container Registry
#       uses: docker/login-action@v3
#       with:
#         registry: ghcr.io
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}

#     - name: Set timestamp
#       id: vars
#       run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

#     - name: Build the Docker image
#       run: |
#         docker build . --file Dockerfile \
#           --tag ghcr.io/kulzer-dental/kdc-experimental-image:latest \
#           --tag ghcr.io/kulzer-dental/kdc-experimental-image:${{ steps.vars.outputs.timestamp }}

#     - name: Push Docker image (latest)
#       if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#       run: docker push ghcr.io/kulzer-dental/kdc-experimental-image:latest

#     - name: Push Docker image (timestamp)
#       if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#       run: docker push ghcr.io/kulzer-dental/kdc-experimental-image:${{ steps.vars.outputs.timestamp }}

#     - name: Azure WebApp Container Deploy
#       uses: azure/webapps-deploy@v3
#       with:
#         app-name: 'kdc-test'
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         images: 'ghcr.io/kulzer-dental/kdc-experimental-image:latest'
